<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="page-title">
    <h1><?php echo Mage::helper('contacts')->__('Reviews List') ?></h1>
</div>
<div class="fieldset">
    <ul class="form-list">
        <?php foreach($this->list as $review) {?>
        <li class="fields">
            <?php echo $review['delivery']; ?>
            &nbsp;
            <?php echo $review['product']; ?>
            &nbsp;
            <?php echo $review['customer_care']; ?>
            &nbsp;
            <?php echo $review['comment']; ?>
        </li>
        <?php } ?>
    </ul>
</div>